### PR TITLE
fix/AuthorizationPopup: Handle invalid container names

### LINKED ISSUE #128: Application does not handle incorrect container names
When sending an authentication request / container request with an invalid container name, the authenticator mobile application crashes. This cannot be handled at the native layer as the native libraries perform only encoding and decoding. The application can handle these invalid container names instead of the current behaviour - app crash

### PR DESCRIPTION
**Pull request by ashwinkumar6**
Fixes #128

### CODE REVIEW

File: SafeAuthenticator/Helpers/Utilities.cs [hunk 1]
```diff
@@ -123,7 +123,20 @@ internal static string FormatContainerName(string containerName)
                 return "Public Names";
             }
 
-            return $"{containerName.Substring(1, 1).ToUpper()}{containerName.Substring(2)}";
+            var formattedText = $"{containerName.Substring(1, 1).ToUpper()}{containerName.Substring(2)}";
+
+            switch (formattedText)
+            {
+                case "Documents":
```
Comment (ravinderjangra) [inline SafeAuthenticator/Helpers/Utilities.cs]: Please convert all the container name in the app into constants and put in a single constant file (already available in code) for uniformity.

File: SafeAuthenticator/Helpers/Constants.cs [hunk 2]
```diff
@@ -7,9 +7,28 @@ internal static class Constants
         internal const int AccStrengthWeak = 8;
         internal const int AccStrengthSomeWhatSecure = 10;
 
+        // ContainerName
+        internal const string AppOwnContainer = "apps/";
```
Comment (ravinderjangra) [inline SafeAuthenticator/Helpers/Constants.cs]: This field `apps/` doesn't represent the AppOwnContainer may be `AppContainer` makes more sense as we are using this constant to check if the container is an app container or not.
